base_url = "https://baherSalama.github.io"
theme = "duckquill"
compile_sass = true
minify_html = true
generate_feeds = true
author = "Baher"
title = "Baher Salama"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
smart_punctuation = true


[extra]
accent_color = "#3584e4"
primary_color_alpha = "rgba(255, 120, 0, 0.2)"
accent_color_dark = "#ff7800"
primary_color_dark_alpha = "rgba(255, 163, 72, 0.2)"
styles = [
  "main.css",
]
[extra.nav]
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/projects/_index.md", name = "Projects" },
]
show_feed = true
show_theme_switcher = true
[extra.footer]
show_copyright = true
